export const deepLLanguages = [
  { code: "bg", name: "Bulgaars" },
  { code: "cs", name: "Tsjechisch" },
  { code: "da", name: "Deens" },
  { code: "de", name: "Duits" },
  { code: "el", name: "Grieks" },
  { code: "en", name: "Engels" },
  { code: "es", name: "Spaans" },
  { code: "et", name: "Ests" },
  { code: "fi", name: "Fins" },
  { code: "fr", name: "Frans" },
  { code: "hu", name: "Hongaars" },
  { code: "id", name: "Indonesisch" },
  { code: "it", name: "Italiaans" },
  { code: "ja", name: "Japans" },
  { code: "lt", name: "Litouws" },
  { code: "lv", name: "Lets" },
  { code: "nl", name: "Nederlands" },
  { code: "pl", name: "Pools" },
  { code: "pt", name: "Portugees" },
  { code: "ro", name: "Roemeens" },
  { code: "ru", name: "Russisch" },
  { code: "sk", name: "Slowaaks" },
  { code: "sl", name: "Sloveens" },
  { code: "sv", name: "Zweeds" },
  { code: "tr", name: "Turks" },
  { code: "uk", name: "Oekraïens" },
  { code: "zh", name: "Chinees" },
];

export const appLanguages = [
  { code: "nl", name: "Nederlands" },
  { code: "fr", name: "Frans" },
  { code: "en", name: "Engels" },
];
